/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointegrador.apresentacao;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import projetointegrador.negocio.CalendarFactory;
import projetointegrador.negocio.Logs;
import projetointegrador.negocio.Usuario;
import projetointegrador.persistencia.DaoGenerico;
import projetointegrador.persistencia.DataBaseException;
import projetointegrador.tableModel.LogsAuditsTableModel;
import projetointegrador.tableModel.UsuarioTableModel;

/**
 *
 * @author enzob
 */
public class TelaTabelaLogs extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaTabelaLogs
     */
    
    private Logs logSelecionado;
    
    public TelaTabelaLogs() throws DataBaseException {
        initComponents();
        carregarTabela("FROM Logs");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLogs = new javax.swing.JTable();
        btAudit = new javax.swing.JButton();
        btLogs = new javax.swing.JButton();
        jCalendarIni = new com.toedter.calendar.JCalendar();
        jCalendarFin = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);

        tabelaLogs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaLogs);

        btAudit.setText("Audits");
        btAudit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAuditActionPerformed(evt);
            }
        });

        btLogs.setText("Logs");
        btLogs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogsActionPerformed(evt);
            }
        });

        jLabel1.setText("Data Inicial:");

        jLabel2.setText("Data Final:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btLogs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btAudit, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCalendarIni, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jCalendarFin, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btLogs)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btAudit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCalendarIni, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCalendarFin, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogsActionPerformed
        
        try {
            carregarTabela("FROM Logs WHERE (level='ERROR' or level='WARN' or level='FATAL') AND dated BETWEEN '" + CalendarString(jCalendarIni) + "' AND '" + CalendarString(jCalendarFin)+"'");
        } catch (DataBaseException ex) {
            Logger.getLogger(TelaTabelaLogs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btLogsActionPerformed

    private void btAuditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAuditActionPerformed
        try {
            carregarTabela("FROM Logs WHERE level='INFO' AND dated BETWEEN '" + CalendarString(jCalendarIni) + "' AND '" + CalendarString(jCalendarFin)+"'");
        } catch (DataBaseException ex) {
            Logger.getLogger(TelaTabelaLogs.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btAuditActionPerformed

    public void carregarTabela(String sql) throws DataBaseException {
        
        //Método para carregar ou atualizar a tabela de usuarios        
        
        DaoGenerico dao = new DaoGenerico();
        List<Logs> lista = dao.read(Logs.class, sql);

        LogsAuditsTableModel tm = new LogsAuditsTableModel(lista);
        tabelaLogs.setModel(tm);

        //Códigos para permitir a seleção na tabela
        ListSelectionModel selectionModel = tabelaLogs.getSelectionModel();
        tabelaLogs.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                int row = tabelaLogs.getSelectedRow();

                if (row >= 0) {
                    LogsAuditsTableModel tableModel = (LogsAuditsTableModel) tabelaLogs.getModel();
                    logSelecionado = tableModel.getListaLogs().get(tabelaLogs.getSelectedRow());
                }
            }
        });
        
    }
    
    public String CalendarString (com.toedter.calendar.JCalendar calendario) {
        
        CalendarFactory c = new CalendarFactory();
        
        String calendarioString = c.CalendarToString(calendario.getCalendar());
        
        String[] dataVetor = c.StringToDayMonthYearAsString(calendarioString);
        
        String dataCompleta = dataVetor[2]+"-"+dataVetor[1]+"-"+dataVetor[0];
        
        return dataCompleta;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAudit;
    private javax.swing.JButton btLogs;
    private com.toedter.calendar.JCalendar jCalendarFin;
    private com.toedter.calendar.JCalendar jCalendarIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaLogs;
    // End of variables declaration//GEN-END:variables
}
