/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointegrador.apresentacao;

import java.awt.Color;
import java.io.UnsupportedEncodingException;
import static java.lang.Integer.parseInt;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.TimeZone;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import projetointegrador.HibernateUtil;
import projetointegrador.negocio.CalendarFactory;
import projetointegrador.negocio.Cargos;
import projetointegrador.negocio.CriptografarSenha;
import projetointegrador.negocio.Usuario;
import projetointegrador.negocio.ValidacaoCpf;
import projetointegrador.persistencia.DaoGenerico;
import projetointegrador.persistencia.DataBaseException;
import projetointegrador.tableModel.UsuarioTableModel;
import projetointegrador.tableModel.UsuarioTableModel;

/**
 *
 * @author enzob
 */
public class TelaCadastroUsuarios extends javax.swing.JInternalFrame {
    
    static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(TelaLogin.class.getName());

    Calendar dataNascCalendar = Calendar.getInstance();
    Calendar dataNascCalendarEditar = Calendar.getInstance();
    
    private Usuario usuarioSelecionado;
    private Usuario atual;
    
    //Booleans para verificação
    
    Boolean isDateOk = false;
    Boolean doesPasswordsMatch = false;
    Boolean isCpfOk = false;
    
    Boolean isDateOkEditar = false;
    Boolean doesPasswordsMatchEditar = false;
    Boolean isCpfOkEditar = false;
    
    Color color;
    
    public TelaCadastroUsuarios(Usuario atual) throws DataBaseException {
        initComponents();
        carregarTabela();        
        this.atual = atual;
        atualizarEditar();
        popularComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelHorizontal = new javax.swing.JTabbedPane();
        jpCadastrar = new javax.swing.JPanel();
        jtFone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfCpf = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        btEnviar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtfDataNasc = new javax.swing.JFormattedTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jpfConfSenha = new javax.swing.JPasswordField();
        jtNome = new javax.swing.JTextField();
        cbSetor = new javax.swing.JComboBox<>();
        jtUsuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jpEditar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbSetorEditar = new javax.swing.JComboBox<>();
        btSalvar = new javax.swing.JButton();
        jtUsuarioEditar = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtfDataNascEditar = new javax.swing.JFormattedTextField();
        jpfSenhaEditar = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        jtFoneEditar = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jtEmailEditar = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jpfConfSenhaEditar = new javax.swing.JPasswordField();
        jtfCpfEditar = new javax.swing.JFormattedTextField();
        jtNomeEditar = new javax.swing.JTextField();
        jpLista = new javax.swing.JPanel();
        btReset = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();

        setClosable(true);

        PainelHorizontal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PainelHorizontalMouseClicked(evt);
            }
        });

        jpCadastrar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("CPF:");

        jLabel1.setText("Usuário:");

        try {
            jtfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCpf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCpfFocusLost(evt);
            }
        });

        jLabel2.setText("Nome Completo:");

        btEnviar.setText("Enviar");
        btEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEnviarActionPerformed(evt);
            }
        });

        jLabel3.setText("Data de Nascimento:");

        jLabel7.setText("Senha:");

        try {
            jtfDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDataNasc.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDataNascFocusLost(evt);
            }
        });

        jLabel4.setText("E-mail:");

        jLabel8.setText("Confirmar Senha:");

        jpfConfSenha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpfConfSenhaFocusLost(evt);
            }
        });

        cbSetor.setModel(new javax.swing.DefaultComboBoxModel<>());

        jtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUsuarioActionPerformed(evt);
            }
        });

        jLabel9.setText("Setor:");

        jLabel5.setText("Telefone:");

        javax.swing.GroupLayout jpCadastrarLayout = new javax.swing.GroupLayout(jpCadastrar);
        jpCadastrar.setLayout(jpCadastrarLayout);
        jpCadastrarLayout.setHorizontalGroup(
            jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastrarLayout.createSequentialGroup()
                        .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jtEmail)
                            .addComponent(jtNome)
                            .addComponent(jtUsuario)
                            .addComponent(jtFone)
                            .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jpfSenha)
                            .addComponent(jpfConfSenha)
                            .addComponent(cbSetor, 0, 171, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastrarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpCadastrarLayout.setVerticalGroup(
            jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastrarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jtfDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jpfConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSetor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(26, 26, 26)
                .addComponent(btEnviar)
                .addGap(53, 53, 53))
        );

        PainelHorizontal.addTab("Cadastrar", jpCadastrar);

        jpEditar.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setText("Nome Completo:");

        cbSetorEditar.setModel(new javax.swing.DefaultComboBoxModel<>());

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        jtUsuarioEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtUsuarioEditarActionPerformed(evt);
            }
        });

        jLabel11.setText("Data de Nascimento:");

        jLabel12.setText("Setor:");

        jLabel13.setText("Senha:");

        jLabel14.setText("Telefone:");

        try {
            jtfDataNascEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfDataNascEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfDataNascEditarFocusLost(evt);
            }
        });

        jLabel15.setText("E-mail:");

        jLabel16.setText("Confirmar Senha:");

        jLabel17.setText("CPF:");

        jLabel18.setText("Usuário:");

        jpfConfSenhaEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jpfConfSenhaEditarFocusLost(evt);
            }
        });

        try {
            jtfCpfEditar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jtfCpfEditar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtfCpfEditarFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jpEditarLayout = new javax.swing.GroupLayout(jpEditar);
        jpEditar.setLayout(jpEditarLayout);
        jpEditarLayout.setHorizontalGroup(
            jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpEditarLayout.createSequentialGroup()
                        .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel16)
                            .addComponent(jLabel12)
                            .addComponent(jLabel10)
                            .addComponent(jLabel18))
                        .addGap(18, 18, 18)
                        .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfDataNascEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jtEmailEditar)
                            .addComponent(jtNomeEditar)
                            .addComponent(jtUsuarioEditar)
                            .addComponent(jtFoneEditar)
                            .addComponent(jtfCpfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(jpfSenhaEditar)
                            .addComponent(jpfConfSenhaEditar)
                            .addComponent(cbSetorEditar, 0, 171, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEditarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpEditarLayout.setVerticalGroup(
            jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpEditarLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtUsuarioEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jtNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(jtfDataNascEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtEmailEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtFoneEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jtfCpfEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jpfSenhaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jpfConfSenhaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSetorEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addComponent(btSalvar)
                .addGap(53, 53, 53))
        );

        PainelHorizontal.addTab("Editar Usuário", jpEditar);

        jpLista.setBackground(new java.awt.Color(255, 255, 255));

        btReset.setText("Resetar senha");

        btExcluir.setText("Excluir conta");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaUsuarios);

        javax.swing.GroupLayout jpListaLayout = new javax.swing.GroupLayout(jpLista);
        jpLista.setLayout(jpListaLayout);
        jpListaLayout.setHorizontalGroup(
            jpListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btExcluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btReset, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jpListaLayout.setVerticalGroup(
            jpListaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpListaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btReset)
                .addGap(18, 18, 18)
                .addComponent(btExcluir)
                .addGap(45, 45, 45))
        );

        PainelHorizontal.addTab("Lista de Usuários", jpLista);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelHorizontal)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelHorizontal, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDataNascFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDataNascFocusLost

        //Função para obrigar a data do calendário ser válida

        dataNascCalendar.setLenient(false);

        try {

            //Funções para transformar a String digitada em valores INT para o objeto Calendar
            
            CalendarFactory cf = new CalendarFactory();
            int[] dmy = cf.StringToDayMonthYear(jtfDataNasc.getText());

            //Verifica se o ano é maior que o ano atual

            if (dmy[2] > Calendar.getInstance(TimeZone.getTimeZone("Brazil/West")).get(Calendar.YEAR)) {
                throw new Exception();
            }

            //Setando o objeto calendar e verificando, caso ocorra um erro a caixa ficará vermelha e o boolean continuara falso

            dataNascCalendar.set(dmy[2], dmy[1], dmy[0], 00, 00, 00);
            jtfDataNasc.setBackground(Color.white);
            isDateOk = true;
            log.info("Data digitada está de acordo");

        } catch (Exception Ex) {

            //Muda a cor do textField caso algo de errado

            jtfDataNasc.setBackground(color = new Color(255, 143, 112));
            JOptionPane.showMessageDialog(null, "A data digitada é inválida");
            isDateOk = false;
            log.warn("Data digitada é inválida");
        }
    }//GEN-LAST:event_jtfDataNascFocusLost

    private void jtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUsuarioActionPerformed

    private void jtfCpfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCpfFocusLost

        //Esquema para verificar se o CPF é válido pelos padrões brasileiros

        try {
            boolean cpfValido = ValidacaoCpf.validarCPF(jtfCpf.getText().replaceAll("[^0-9]",""));

            if (cpfValido == false) {
                throw new Exception();
            }

            jtfCpf.setBackground(color.white);
            isCpfOk = true;
            log.info("CPF válido");            

        } catch (Exception ex) {
            jtfCpf.setBackground(color = new Color(255, 143, 112));
            JOptionPane.showMessageDialog(null, "O CPF digitado é inválido");
            isCpfOk = false;
            log.warn("CPF inválido");
        }

    }//GEN-LAST:event_jtfCpfFocusLost

    private void btEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEnviarActionPerformed

        //Criação de um objeto usuário novo caso as condições estejam de acordo
        if (isDateOk == true && doesPasswordsMatch == true && isCpfOk == true) {

            Session sessao = null;
            try {
                
                CriptografarSenha cripto = new CriptografarSenha();
                String senhaCriptografada = cripto.cripto(jpfSenha.getText());

                
                Usuario login = new Usuario(jtUsuario.getText(), jtNome.getText(), dataNascCalendar, jtEmail.getText(), jtFone.getText(), jtfCpf.getText(), senhaCriptografada, (Cargos)cbSetor.getSelectedItem());
                
                //Salva o novo usuário no banco de dados
                
                DaoGenerico dao = new DaoGenerico ();
                dao.create(login);
                
                carregarTabela();
                JOptionPane.showMessageDialog(null, "Cadastro efetuado com sucesso!");
                log.info("Cadastro efetuado com sucesso, usuario: " + jtUsuario.getText());
                
            } catch (HibernateException hibEx) {
                hibEx.printStackTrace();
                log.error("Erro no hibernate ao cadastrar usuário");
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(TelaCadastroUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(TelaCadastroUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (DataBaseException ex) {
                Logger.getLogger(TelaCadastroUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Algum campo está inválido");
            log.error("Erro nos campos do cadastro");
        }

    }//GEN-LAST:event_btEnviarActionPerformed

    private void jpfConfSenhaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpfConfSenhaFocusLost

        //Esquema para verificar se as senhas coincidem

        try {
            if (!jpfSenha.getText().equals(jpfConfSenha.getText())) {
                throw new Exception();
            }

            jpfConfSenha.setBackground (Color.white);
            doesPasswordsMatch = true;

        } catch (Exception ex) {
            jpfConfSenha.setBackground(color = new Color(255, 143, 112));
            JOptionPane.showMessageDialog(null, "As senhas não coincidem");
            doesPasswordsMatch = false;
            log.warn("Senhas digitadas não são iguais");
        }

    }//GEN-LAST:event_jpfConfSenhaFocusLost

    private void PainelHorizontalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PainelHorizontalMouseClicked
        
        
        
    }//GEN-LAST:event_PainelHorizontalMouseClicked

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        
        try {
            DaoGenerico <Usuario> dao = new DaoGenerico <> ();
            dao.delete(Usuario.class, "FROM Usuario WHERE id=" + usuarioSelecionado.getId());
            carregarTabela();
            log.info("Usuario deletado com sucesso: " + usuarioSelecionado.getUsuario());
        } catch (DataBaseException ex) {
            Logger.getLogger(TelaCadastroUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            log.error("Não foi possivel deletar o usuário: " + usuarioSelecionado.getUsuario());
        }
        
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
   
        DaoGenerico dao = new DaoGenerico();
        Usuario novo = atual;
        if (isDateOkEditar == true && doesPasswordsMatchEditar == true && isCpfOkEditar == true) {
             
            try {
                novo.setUsuario(jtUsuarioEditar.getText());
                novo.setNomeCompleto(jtNomeEditar.getText());
                novo.setDataNasc(dataNascCalendarEditar);
                novo.setEmail(jtEmailEditar.getText());
                novo.setCpf(jtfCpfEditar.getText());
                
                //Caso senha não for vazio, criptografa a nova e atualiza
                
                if (!jpfSenhaEditar.getText().equals("")) {
                    
                    CriptografarSenha cripto = new CriptografarSenha();
                    String newSenha = "";
                    try {
                        newSenha = cripto.cripto(jpfSenhaEditar.getText());
                    } catch (NoSuchAlgorithmException ex) {
                        Logger.getLogger(TelaCadastroUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (UnsupportedEncodingException ex) {
                        Logger.getLogger(TelaCadastroUsuarios.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    
                    novo.setSenha(newSenha);
                }
                
                dao.edit(novo, "FROM Usuario WHERE usuario='"+atual.getUsuario()+"'");
                System.out.println("chegou // " + novo.getNomeCompleto());
                carregarTabela();
            } catch (DataBaseException ex) {
                Logger.getLogger(TelaCadastroUsuarios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_btSalvarActionPerformed

    private void jtUsuarioEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtUsuarioEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtUsuarioEditarActionPerformed

    private void jtfDataNascEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDataNascEditarFocusLost
        
        //Função para obrigar a data do calendário ser válida

        dataNascCalendarEditar.setLenient(false);

        try {

            //Funções para transformar a String digitada em valores INT para o objeto Calendar
            
            CalendarFactory cf = new CalendarFactory();
            int[] dmy = cf.StringToDayMonthYear(jtfDataNascEditar.getText());

            //Verifica se o ano é maior que o ano atual

            if (dmy[2] > Calendar.getInstance(TimeZone.getTimeZone("Brazil/West")).get(Calendar.YEAR)) {
                throw new Exception();
            }

            //Setando o objeto calendar e verificando, caso ocorra um erro a caixa ficará vermelha e o boolean continuara falso

            dataNascCalendarEditar.set(dmy[2], dmy[1], dmy[0], 00, 00, 00);
            jtfDataNascEditar.setBackground(Color.white);
            isDateOkEditar = true;
            log.info("Data digitada está de acordo");

        } catch (Exception Ex) {

            //Muda a cor do textField caso algo de errado

            jtfDataNascEditar.setBackground(color = new Color(255, 143, 112));
            JOptionPane.showMessageDialog(null, "A data digitada é inválida");
            isDateOkEditar = false;
            log.warn("Data digitada é inválida");
        }
        
    }//GEN-LAST:event_jtfDataNascEditarFocusLost

    private void jpfConfSenhaEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jpfConfSenhaEditarFocusLost
        
//Esquema para verificar se as senhas coincidem

        try {
            if (!jpfSenhaEditar.getText().equals(jpfConfSenhaEditar.getText())) {
                throw new Exception();
            }

            jpfConfSenhaEditar.setBackground (Color.white);
            doesPasswordsMatchEditar = true;

        } catch (Exception ex) {
            jpfConfSenhaEditar.setBackground(color = new Color(255, 143, 112));
            JOptionPane.showMessageDialog(null, "As senhas não coincidem");
            doesPasswordsMatchEditar = false;
            log.warn("Senhas digitadas não são iguais");
        }
        
    }//GEN-LAST:event_jpfConfSenhaEditarFocusLost

    private void jtfCpfEditarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfCpfEditarFocusLost
        
        //Esquema para verificar se o CPF é válido pelos padrões brasileiros

        try {
            boolean cpfValido = ValidacaoCpf.validarCPF(jtfCpfEditar.getText().replaceAll("[^0-9]",""));

            if (cpfValido == false) {
                throw new Exception();
            }

            jtfCpfEditar.setBackground(color.white);
            isCpfOkEditar = true;
            log.info("CPF válido");            

        } catch (Exception ex) {
            jtfCpfEditar.setBackground(color = new Color(255, 143, 112));
            JOptionPane.showMessageDialog(null, "O CPF digitado é inválido");
            isCpfOkEditar = false;
            log.warn("CPF inválido");
        }
        
    }//GEN-LAST:event_jtfCpfEditarFocusLost

    public void carregarTabela() throws DataBaseException {
        
        //Método para carregar ou atualizar a tabela de usuarios        
        
        DaoGenerico dao = new DaoGenerico();
        List<Usuario> lista = dao.read(Usuario.class, "FROM Usuario");

        UsuarioTableModel tm = new UsuarioTableModel(lista);
        tabelaUsuarios.setModel(tm);

        //Códigos para permitir a seleção na tabela
        ListSelectionModel selectionModel = tabelaUsuarios.getSelectionModel();
        tabelaUsuarios.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {

                int row = tabelaUsuarios.getSelectedRow();

                if (row >= 0) {
                    UsuarioTableModel tableModel = (UsuarioTableModel) tabelaUsuarios.getModel();
                    usuarioSelecionado = tableModel.getListaUsuario().get(tabelaUsuarios.getSelectedRow());
                }
                System.out.println(usuarioSelecionado.getId());
            }
        });
        
    }
    
    public void atualizarEditar () {
        
        //Define os campos da tela de Editar com os dados do usuário logado
        
        jtUsuarioEditar.setText(atual.getUsuario());
        jtNomeEditar.setText(atual.getNomeCompleto());
        
        //Algoritmo para acertar o dia e mes
        CalendarFactory cl = new CalendarFactory();
        String data = cl.CalendarToString(atual.getDataNasc());
        
        jtfDataNascEditar.setText(data);
        jtEmailEditar.setText(atual.getEmail());
        jtFoneEditar.setText(atual.getFone());
        jtfCpfEditar.setText(atual.getCpf());
        
    }
    
    public void popularComboBox () {
        
        cbSetor.removeAllItems();
        cbSetorEditar.removeAllItems();
        
        DaoGenerico dao = new DaoGenerico();
        List<Cargos> lista = new ArrayList();
        lista = dao.read(Cargos.class, "FROM Cargos");
        
        /*DefaultComboBoxModel model = new DefaultComboBoxModel(lista);
        cbSetor.setModel(model);*/
        
        for (int i = 0; i < lista.size(); i++) {
            cbSetor.addItem(lista.get(i));
            cbSetorEditar.addItem(lista.get(i));
        }
        
    }
    
    public void setarLabels (boolean permitir) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane PainelHorizontal;
    private javax.swing.JButton btEnviar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox<Cargos> cbSetor;
    private javax.swing.JComboBox<Cargos> cbSetorEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpCadastrar;
    private javax.swing.JPanel jpEditar;
    private javax.swing.JPanel jpLista;
    private javax.swing.JPasswordField jpfConfSenha;
    private javax.swing.JPasswordField jpfConfSenhaEditar;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JPasswordField jpfSenhaEditar;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTextField jtEmailEditar;
    private javax.swing.JTextField jtFone;
    private javax.swing.JTextField jtFoneEditar;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtNomeEditar;
    private javax.swing.JTextField jtUsuario;
    private javax.swing.JTextField jtUsuarioEditar;
    private javax.swing.JFormattedTextField jtfCpf;
    private javax.swing.JFormattedTextField jtfCpfEditar;
    private javax.swing.JFormattedTextField jtfDataNasc;
    private javax.swing.JFormattedTextField jtfDataNascEditar;
    private javax.swing.JTable tabelaUsuarios;
    // End of variables declaration//GEN-END:variables
}
